[project]
name = "langgraph-learning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Karan Kumar Sharma", email = "sk5485633@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
langgraph-learning = "langgraph_learning:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
